[package]
name = "policy-metadata-helper"
version = "1.0.5"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
versions = { workspace = true }
k8s-openapi = { workspace = true }
