maxSeverity:
  critical:
    total: 5
  high:
    total: 30
  medium:
    total: 50
  low:
    total: 100
  unknown:
    total: 200
ignoreMissingVulnerabilityReport: false
vulnerabilityReportNamespace: sbomscanner
platform:
  arch: amd64
  os: linux
