[package]
name = "image-cve-policy"
version = "0.5.4"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
k8s-openapi = { workspace = true, features = ["schemars"] }
kubewarden-policy-sdk = { workspace = true }
lazy_static = { workspace = true }
mockall = { workspace = true }
oci-spec = { workspace = true }
rstest = { workspace = true }
schemars = "1.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serial_test = { workspace = true }
slog = { workspace = true }
thiserror = { workspace = true }
