[package]
name = "verify-image-signatures"
version = "1.0.5"
authors = ["Kubewarden Developers <cncf-kubewarden-maintainers@lists.cncf.io>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
k8s-openapi = { workspace = true }
kubewarden-policy-sdk = { workspace = true }
lazy_static = { workspace = true }
pem = "3.0.4"
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
validator = { version = "0.20", features = ["derive"] }
wildmatch = "2.5.0"

[dev-dependencies]
mockall = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }
