[package]
name = "user-group-psp"
version = "1.1.4"
authors = ["Kubewarden developers <cncf-kubewarden-maintainers@lists.cncf.io>", "Jos√© Guilherme Vanz <jguilhermevanz@suse.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
k8s-openapi = { workspace = true }
kubewarden-policy-sdk = { workspace = true }
lazy_static = { workspace = true }
oci-spec = { workspace = true }
serde = { features = ["derive"], workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
jsonpath_lib = { workspace = true }
rstest = { workspace = true }
