[package]
name = "volumemounts-policy"
version = "1.0.6"
authors = ["VÃ­ctor Cuadrado Juan <vcuadradojuan@suse.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
k8s-openapi = { workspace = true }
kubewarden-policy-sdk = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
slog = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }
