name: CI crates

on:
  push:
    paths:
      - "policies/crates/**"
  pull_request:
    paths:
      - "policies/crates/**"

jobs:
  calculate-crates-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: List crate folders
        id: set-matrix
        run: |
          CRATES=$(ls -1 policies/crates | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"crate\":$CRATES}" >> $GITHUB_OUTPUT

  check:
    needs: calculate-crates-matrix
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.calculate-crates-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Run cargo check"
        run: |
          make -C policies/crates/${{ matrix.crate }} check

  test:
    needs: calculate-crates-matrix
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.calculate-crates-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Run cargo test"
        run: |
          make -C policies/crates/${{ matrix.crate }} test

  fmt:
    needs: calculate-crates-matrix
    name: Rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.calculate-crates-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Run cargo fmt"
        run: |
          make -C policies/crates/${{ matrix.crate }} fmt

  clippy:
    needs: calculate-crates-matrix
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.calculate-crates-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Run cargo clippy"
        run: |
          make -C policies/crates/${{ matrix.crate }} lint

  spelling:
    needs: calculate-crates-matrix
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.calculate-crates-matrix.outputs.matrix)}}
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install typos Spell check
        uses: crate-ci/typos@06d010dfe4c84fdab1a25ea02b57b3585018ba80 # v1.42.3
        with:
          files: policies/crates/${{ matrix.crate }}/**
