on:
  workflow_call:
    inputs:
      policy-working-dir:
        description: "Working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: "."

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Policy linter
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build policy
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} policy.wasm
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Policy unit tests
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Policy integration test
        shell: bash
        run: |
          make -C ${{ inputs.policy-working-dir}} e2e-tests
